// ============================================================================
// HD PRODUCTS LIST
// ----------------------------------------------------------------------------
// SOURCE OF TRUTH: image-pipeline/final_manifest.json (entries with hd: true).
//
// This file is GENERATED. Do not edit by hand. To add or remove an HD product,
// flip the `hd` flag on the manifest entry and re-run:
//   node scripts/generate-hd-products.js
// (also runs as part of `npm run prebuild`).
//
// Single source of truth for both the product catalog and the HD_BASE_IDS set
// — eliminates the historical drift where products[] and HD_BASE_IDS could
// silently diverge across commits.
// ============================================================================

export const HD_PRODUCTS = [
  // bookshelves-bright
  { id: 'well-lit-modern-boardroom-wooden-floor-framed-artwork-wall-cadb4573-hd', name: "Bright Bookshelf #1", category: 'bookshelves-bright' },
  { id: 'cozy-room-white-bookcase-filled-books-lamp-floral-decor-9f1f1030-hd', name: "Bright Bookshelf #2", category: 'bookshelves-bright' },
  { id: 'bright-office-space-white-bookshelf-filled-books-decorative-3ffd4266-hd', name: "Bright Bookshelf #4", category: 'bookshelves-bright' },
  { id: 'bright-room-soft-blue-walls-bookshelf-books-coastal-artwork-f1adc4b4-hd', name: "Bright Bookshelf #6", category: 'bookshelves-bright' },
  { id: 'light-green-room-bookshelf-framed-art-wall-cozy-seating-area-a5bf616e-hd', name: "Bright Bookshelf #7", category: 'bookshelves-bright' },
  { id: 'cozy-home-office-gallery-wall-framed-pictures-wooden-a530a6bd-hd', name: "Bright Bookshelf #10", category: 'bookshelves-bright' },
  { id: 'cozy-living-space-wooden-bookshelf-filled-books-natural-655d83a2-hd', name: "Bright Bookshelf #11", category: 'bookshelves-bright' },
  { id: 'modern-white-bookshelf-books-green-plant-well-lit-room-warm-768dd75b-hd', name: "Bright Bookshelf #12", category: 'bookshelves-bright' },
  { id: 'modern-boardroom-dark-bookshelf-filled-books-potted-plant-520fb23f-hd', name: "Bright Bookshelf #13", category: 'bookshelves-bright' },
  { id: 'bright-minimalist-room-white-wall-tall-bookshelf-filled-fe743315-hd', name: "Bright Bookshelf #19", category: 'bookshelves-bright' },
  { id: 'modern-bookshelf-wooden-shelves-filled-books-decor-beside-7ae6b429-hd', name: "Bright Bookshelf #20", category: 'bookshelves-bright' },
  { id: 'modern-shelving-unit-books-decor-illuminated-natural-light-819250d3-hd', name: "Bright Bookshelf #23", category: 'bookshelves-bright' },
  { id: 'cozy-corner-light-wood-bench-black-shelves-large-windows-0d990fd2-hd', name: "Bright Bookshelf #24", category: 'bookshelves-bright' },
  { id: 'cozy-living-room-gray-armchair-white-bookshelves-filled-801adfcd-hd', name: "Bright Bookshelf #29", category: 'bookshelves-bright' },
  { id: 'bright-room-modern-white-bookshelf-filled-books-fiddle-leaf-630c248d-hd', name: "Bright Bookshelf #42", category: 'bookshelves-bright' },
  { id: 'white-bookshelf-filled-colorful-books-beside-cozy-armchair-c56664dc-hd', name: "Bright Bookshelf #51", category: 'bookshelves-bright' },
  { id: 'bright-room-wooden-bookcase-filled-books-potted-plant-corner-0033a355-hd', name: "Bright Bookshelf #70", category: 'bookshelves-bright' },
  { id: 'well-organized-bookshelf-various-books-decorative-items-2e6909dc-hd', name: "Bright Bookshelf #88", category: 'bookshelves-bright' },
  { id: 'well-organized-bookshelf-various-books-decorative-items-6ca36ef8-hd', name: "Bright Bookshelf #89", category: 'bookshelves-bright' },
  { id: 'wooden-shelf-collection-vintage-books-vase-fresh-flowers-1d3f1286-hd', name: "Bright Bookshelf #1", category: 'bookshelves-bright' },
  { id: 'wooden-bookshelf-filled-books-single-eucalyptus-plant-left-65fd44ae-hd', name: "Bright Bookshelf #36", category: 'bookshelves-bright' },
  { id: 'cozy-home-library-wooden-bookshelves-filled-books-large-0612bee9-hd', name: "Bright Bookshelf #43", category: 'bookshelves-bright' },
  { id: 'bright-room-white-bookshelf-filled-books-small-plants-12d905e9-hd', name: "Bright Bookshelf #73", category: 'bookshelves-bright' },
  { id: 'wooden-shelves-displaying-variety-books-warm-lighting-small-e1797426-hd', name: "Bright Bookshelf #44", category: 'bookshelves-bright' },
  { id: 'modern-bookshelf-books-decorative-items-soft-color-palette-b6c085af-hd', name: "Bright Bookshelf #73", category: 'bookshelves-bright' },
  { id: 'wooden-bookshelf-filled-books-small-plant-warm-lighting-06982916-hd', name: "Bright Bookshelf #33", category: 'bookshelves-bright' },
  // bookshelves-dark
  { id: 'cozy-corner-bookshelf-potted-plant-warm-light-earthy-yellow-b12af81f-hd', name: "Dark Bookshelf #2", category: 'bookshelves-dark' },
  { id: 'warm-brown-wall-features-wooden-shelf-books-decorative-items-d08efe6e-hd', name: "Dark Bookshelf #6", category: 'bookshelves-dark' },
  { id: 'cozy-interior-corner-wooden-shelf-two-framed-pictures-floor-032082d3-hd', name: "Dark Bookshelf #7", category: 'bookshelves-dark' },
  { id: 'cozy-interior-terracotta-walls-potted-plant-wooden-bookshelf-60a780cd-hd', name: "Dark Bookshelf #8", category: 'bookshelves-dark' },
  { id: 'cozy-living-space-brick-wall-large-window-plants-bookshelf-3a9441d7-hd', name: "Dark Bookshelf #9", category: 'bookshelves-dark' },
  { id: 'two-wooden-bookshelves-filled-various-books-small-table-2bbf59f3-hd', name: "Dark Bookshelf #25", category: 'bookshelves-dark' },
  { id: 'black-bookshelves-filled-books-warm-light-hanging-ceiling-45195d0f-hd', name: "Dark Bookshelf #27", category: 'bookshelves-dark' },
  { id: 'dark-library-wooden-bookshelves-floor-lamp-globe-warm-efbf26c2-hd', name: "Dark Bookshelf #28", category: 'bookshelves-dark' },
  { id: 'wooden-bookshelf-filled-old-books-green-lamp-illuminating-f61f81f5-hd', name: "Dark Bookshelf #37", category: 'bookshelves-dark' },
  { id: 'well-organized-bookshelf-colorful-books-plants-natural-light-4df78da9-hd', name: "Dark Bookshelf #40", category: 'bookshelves-dark' },
  { id: 'well-organized-bookshelf-various-books-hanging-plants-warm-9e1ff03f-hd', name: "Dark Bookshelf #41", category: 'bookshelves-dark' },
  // wall-shelves-bright
  { id: 'two-wooden-shelves-against-white-wall-one-books-plant-other-d50bd43b-hd', name: "Bright Wall Shelf #1", category: 'wall-shelves-bright' },
  { id: 'bright-room-wooden-shelves-displaying-potted-plants-books-73bc1e72-hd', name: "Bright Wall Shelf #2", category: 'wall-shelves-bright' },
  { id: 'bright-white-wall-floating-shelves-displaying-books-small-f818d481-hd', name: "Bright Wall Shelf #3", category: 'wall-shelves-bright' },
  { id: 'bright-modern-interior-white-wall-shelves-holding-books-35facfd9-hd', name: "Bright Wall Shelf #10", category: 'wall-shelves-bright' },
  { id: 'wooden-shelves-books-small-plants-arranged-white-wall-clean-a10bbe5d-hd', name: "Bright Wall Shelf #12", category: 'wall-shelves-bright' },
  { id: 'light-wood-shelves-books-potted-plants-arranged-minimalist-0b690705-hd', name: "Bright Wall Shelf #13", category: 'wall-shelves-bright' },
  { id: 'light-colored-minimalist-shelves-books-small-plants-softly-a8eadbc7-hd', name: "Bright Wall Shelf #16", category: 'wall-shelves-bright' },
  { id: 'three-white-shelves-potted-plants-books-against-bright-white-d4936794-hd', name: "Bright Wall Shelf #17", category: 'wall-shelves-bright' },
  { id: 'minimalist-interior-light-beige-walls-dark-floating-shelves-9fd169f8-hd', name: "Bright Wall Shelf #20", category: 'wall-shelves-bright' },
  { id: 'marble-wall-subtle-gold-veining-shelf-decorative-vases-books-81ac7934-hd', name: "Bright Wall Shelf #21", category: 'wall-shelves-bright' },
  { id: 'minimalist-wooden-shelf-displaying-three-framed-artworks-two-d41ed1d2-hd', name: "Bright Wall Shelf #28", category: 'wall-shelves-bright' },
  { id: 'bright-white-shelves-filled-various-plants-books-small-pot-fbe0d393-hd', name: "Bright Wall Shelf #29", category: 'wall-shelves-bright' },
  { id: 'minimalist-shelf-potted-plants-framed-art-against-light-wall-007604e6-hd', name: "Bright Wall Shelf #49", category: 'wall-shelves-bright' },
  { id: 'bright-minimalist-interior-wooden-shelves-decorative-plants-14e4abed-hd', name: "Bright Wall Shelf #50", category: 'wall-shelves-bright' },
  { id: 'minimalist-interior-wooden-shelf-holding-books-potted-plant-47fe79fc-hd', name: "Bright Wall Shelf #51", category: 'wall-shelves-bright' },
  { id: 'minimalist-shelving-books-dried-plants-neutral-tones-softly-6536c05c-hd', name: "Bright Wall Shelf #54", category: 'wall-shelves-bright' },
  { id: 'minimalist-shelf-various-vases-neutral-tones-soft-greenery-e6eddef7-hd', name: "Bright Wall Shelf #55", category: 'wall-shelves-bright' },
  // wall-shelves-dark
  { id: 'four-wooden-shelves-mounted-concrete-wall-books-small-plants-41490ffa-hd', name: "Dark Wall Shelf #1", category: 'wall-shelves-dark' },
  { id: 'modern-black-shelving-unit-decorative-items-illuminated-warm-f15b51bb-hd', name: "Dark Wall Shelf #2", category: 'wall-shelves-dark' },
  { id: 'three-black-floating-shelves-against-textured-gray-wall-c68df379-hd', name: "Dark Wall Shelf #4", category: 'wall-shelves-dark' },
  { id: 'dark-wall-three-minimalist-shelves-holding-potted-plants-e6541565-hd', name: "Dark Wall Shelf #6", category: 'wall-shelves-dark' },
  { id: 'four-wooden-shelves-mounted-concrete-wall-illuminated-warm-c546d9a7-hd', name: "Dark Wall Shelf #17", category: 'wall-shelves-dark' },
  { id: 'minimalist-wall-two-black-shelves-holding-books-potted-25ab5762-hd', name: "Dark Wall Shelf #19", category: 'wall-shelves-dark' },
  { id: 'wooden-shelves-potted-plant-books-illuminated-soft-overhead-59ab3ef2-hd', name: "Dark Wall Shelf #26", category: 'wall-shelves-dark' },
  { id: 'well-lit-corner-wooden-shelves-displaying-various-plants-22af5d26-hd', name: "Dark Wall Shelf #28", category: 'wall-shelves-dark' },
  { id: 'wooden-shelves-books-potted-plants-illuminated-warm-light-bbc530de-hd', name: "Dark Wall Shelf #29", category: 'wall-shelves-dark' },
  { id: 'green-wall-wooden-shelves-displaying-books-potted-plants-ef5f27c9-hd', name: "Dark Wall Shelf #42", category: 'wall-shelves-dark' },
  { id: 'modern-green-wall-wooden-shelves-books-decorative-plants-63f91dcd-hd', name: "Dark Wall Shelf #51", category: 'wall-shelves-dark' },
  { id: 'minimalist-interior-white-wall-shelves-maps-potted-plants-09679628-hd', name: "Dark Wall Shelf #34", category: 'wall-shelves-dark' },
  // coffee-shops
  { id: 'spacious-concrete-room-wooden-shelf-coffee-machine-large-4ed44153-hd', name: "Coffee Shop #3", category: 'coffee-shops' },
  { id: 'cozy-indoor-setting-large-arched-windows-wooden-chairs-c0962d00-hd', name: "Coffee Shop #4", category: 'coffee-shops' },
  { id: 'cozy-cafe-interior-wooden-tables-hanging-plants-large-918575fc-hd', name: "Coffee Shop #10", category: 'coffee-shops' },
  { id: 'cafe-interior-wooden-tables-potted-plants-large-windows-cb3a81f8-hd', name: "Coffee Shop #12", category: 'coffee-shops' },
  { id: 'two-leather-armchairs-modern-studio-warm-pendant-lighting-b06c7847-hd', name: "Coffee Shop #19", category: 'coffee-shops' },
  { id: 'modern-cafe-interior-wooden-tables-white-chairs-greenery-7853cbf9-hd', name: "Coffee Shop #22", category: 'coffee-shops' },
  { id: 'interior-industrial-coffee-shop-wooden-counters-hanging-c082f600-hd', name: "Coffee Shop #29", category: 'coffee-shops' },
  { id: 'interior-cozy-cafe-wood-panelled-walls-wooden-tables-hanging-b174c12d-hd', name: "Coffee Shop #13", category: 'coffee-shops' },
  // conference-rooms
  { id: 'modern-boardroom-geometric-wall-designs-warm-lighting-large-0832df1f-hd', name: "Conference Room #1", category: 'conference-rooms' },
  { id: 'spacious-boardroom-large-wooden-table-surrounded-gray-chairs-ae0bacd2-hd', name: "Conference Room #2", category: 'conference-rooms' },
  { id: 'bright-dining-room-wooden-table-woven-chairs-large-windows-3b0e2057-hd', name: "Conference Room #4", category: 'conference-rooms' },
  { id: 'spacious-boardroom-light-blue-wall-wooden-table-woven-chairs-c4287666-hd', name: "Conference Room #5", category: 'conference-rooms' },
  { id: 'modern-boardroom-long-wooden-table-surrounded-leather-chairs-bcc87adf-hd', name: "Conference Room #6", category: 'conference-rooms' },
  { id: 'bright-boardroom-marble-wall-large-windows-city-skyline-view-90923d4f-hd', name: "Conference Room #21", category: 'conference-rooms' },
  { id: 'bright-boardroom-large-marble-table-leather-chairs-large-19e98ba3-hd', name: "Conference Room #22", category: 'conference-rooms' },
  { id: 'boardroom-large-wooden-table-black-chairs-green-wall-plants-533d7286-hd', name: "Conference Room #3", category: 'conference-rooms' },
  // libraries
  { id: 'cozy-library-wooden-shelves-filled-books-stone-fireplace-1854e117-hd', name: "Library #17", category: 'libraries' },
  { id: 'luxurious-library-dark-wood-shelves-filled-books-plush-red-e0a2672b-hd', name: "Library #18", category: 'libraries' },
  { id: 'spacious-boardroom-marble-floor-large-windows-bookshelves-5cadeaca-hd', name: "Library #23", category: 'libraries' },
  { id: 'library-wooden-shelves-filled-books-warm-lighting-sconces-a8054378-hd', name: "Library #34", category: 'libraries' },
  // urban-lofts
  { id: 'spacious-industrial-gallery-exposed-brick-walls-soft-5035b7a4-hd', name: "Urban Loft #10", category: 'urban-lofts' },
  { id: 'interior-view-arched-windows-warm-orange-wall-natural-light-bcba9893-hd', name: "Urban Loft #18", category: 'urban-lofts' },
  { id: 'industrial-interior-green-accent-wall-large-windows-potted-60c0bbc9-hd', name: "Urban Loft #20", category: 'urban-lofts' },
  { id: 'interior-room-bright-green-walls-large-windows-allowing-ea1e06e2-hd', name: "Urban Loft #26", category: 'urban-lofts' },
  { id: 'bright-corporate-boardroom-large-windows-wood-wall-accents-2f8bd261-hd', name: "Urban Loft #28", category: 'urban-lofts' },
  { id: 'spacious-room-concrete-wall-large-windows-letting-natural-70f2b20e-hd', name: "Urban Loft #31", category: 'urban-lofts' },
  { id: 'cozy-loft-exposed-brick-walls-wooden-beams-dark-sofa-coffee-1410b31e-hd', name: "Urban Loft #38", category: 'urban-lofts' },
  { id: 'bright-room-white-sofa-large-windows-showing-city-skyline-9aa407ee-hd', name: "Urban Loft #45", category: 'urban-lofts' },
  // office-spaces
  { id: 'contemporary-office-interior-wooden-desk-floral-arrangements-51d86333-hd', name: "Office Space #49", category: 'office-spaces' },
  { id: 'bright-office-space-white-desk-pastel-file-organizers-potted-c4099bfc-hd', name: "Office Space #7", category: 'office-spaces' },
  { id: 'minimalist-office-space-large-window-desk-chair-potted-plant-17c9948c-hd', name: "Office Space #20", category: 'office-spaces' },
  { id: 'bright-office-interior-wooden-desk-white-chair-light-wood-b7c2b0bd-hd', name: "Office Space #22", category: 'office-spaces' },
  { id: 'bright-minimalist-office-white-wall-sleek-desk-potted-plants-b06d8d28-hd', name: "Office Space #23", category: 'office-spaces' },
  { id: 'minimalist-office-wooden-desk-laptop-potted-plant-2cce817c-hd', name: "Office Space #29", category: 'office-spaces' },
  { id: 'bright-minimalist-office-white-sofa-plants-large-windows-624d1a51-hd', name: "Office Space #41", category: 'office-spaces' },
  { id: 'boardroom-wooden-table-chairs-bookshelves-illuminated-45b44bc0-hd', name: "Office Space #1", category: 'office-spaces' },
  { id: 'bright-boardroom-light-wood-table-white-walls-large-blank-ca82f1db-hd', name: "Office Space #2", category: 'office-spaces' },
  { id: 'bright-office-marble-desk-glass-shelves-large-windows-0df5a703-hd', name: "Office Space #3", category: 'office-spaces' },
  { id: 'modern-executive-office-multiple-screens-displaying-data-9747a15a-hd', name: "Office Space #5", category: 'office-spaces' },
  { id: 'contemporary-office-setup-white-shelving-green-plants-ae13c020-hd', name: "Office Space #8", category: 'office-spaces' },
  { id: 'spacious-modern-office-large-windows-marble-flooring-leather-122f39e6-hd', name: "Office Space #10", category: 'office-spaces' },
  { id: 'luxurious-executive-office-dark-wood-furniture-marble-b4ab92ad-hd', name: "Office Space #12", category: 'office-spaces' },
  { id: 'modern-office-glass-desk-black-chair-large-windows-82ecddc4-hd', name: "Office Space #15", category: 'office-spaces' },
  { id: 'modern-office-interior-large-windows-showcasing-city-skyline-3b5d303b-hd', name: "Office Space #16", category: 'office-spaces' },
  { id: 'bright-office-corner-wooden-shelves-blue-books-computer-6c6d4cb2-hd', name: "Office Space #19", category: 'office-spaces' },
  { id: 'bright-office-workspace-organized-shelves-clean-desk-natural-f4451e7f-hd', name: "Office Space #20", category: 'office-spaces' },
  { id: 'spacious-modern-office-wooden-desk-black-chair-minimalist-7559fb22-hd', name: "Office Space #24", category: 'office-spaces' },
  { id: 'bright-office-space-wooden-accent-wall-desk-computer-large-a06e723f-hd', name: "Office Space #28", category: 'office-spaces' },
  { id: 'bright-minimalist-interior-white-wall-wooden-shelves-small-b2880b29-hd', name: "Office Space #33", category: 'office-spaces' },
  { id: 'wood-paneled-wall-shelves-displaying-books-potted-plants-c8197647-hd', name: "Office Space #34", category: 'office-spaces' },
  { id: 'warm-wood-paneling-two-shelves-holding-books-potted-plants-7838ced1-hd', name: "Office Space #35", category: 'office-spaces' },
  { id: 'bright-boardroom-large-oval-table-white-chairs-glass-walls-6c61e55f-hd', name: "Office Space #36", category: 'office-spaces' },
  { id: 'minimalist-office-soft-green-walls-white-desk-modern-chair-17a026a1-hd', name: "Office Space #38", category: 'office-spaces' },
  { id: 'contemporary-office-interior-wooden-desk-ergonomic-chair-88b9a371-hd', name: "Office Space #43", category: 'office-spaces' },
  { id: 'contemporary-office-interior-concrete-walls-wooden-desks-c1a367ce-hd', name: "Office Space #59", category: 'office-spaces' },
  { id: 'modern-office-space-white-desk-black-chair-textured-gray-531627e6-hd', name: "Office Space #62", category: 'office-spaces' },
  { id: 'bright-office-interior-wooden-desk-ergonomic-chair-green-d155b815-hd', name: "Office Space #63", category: 'office-spaces' },
  { id: 'bright-office-space-wooden-accent-wall-desk-chair-neutral-03a8e6f9-hd', name: "Office Space #66", category: 'office-spaces' },
  { id: 'modern-executive-office-dark-wood-desk-leather-chair-marble-5ce9300b-hd', name: "Office Space #69", category: 'office-spaces' },
  { id: 'contemporary-office-interior-wooden-desk-black-chair-large-217ebb58-hd', name: "Office Space #70", category: 'office-spaces' },
  { id: 'modern-office-wooden-desk-ergonomic-chair-large-windows-72da6fbb-hd', name: "Office Space #71", category: 'office-spaces' },
  { id: 'dark-wood-paneling-polished-executive-desk-black-chair-9add84f3-hd', name: "Office Space #77", category: 'office-spaces' },
  { id: 'modern-executive-office-wooden-desk-leather-chair-large-57955a1d-hd', name: "Office Space #84", category: 'office-spaces' },
  { id: 'modern-office-dark-polished-desk-large-windows-showcasing-6357a953-hd', name: "Office Space #89", category: 'office-spaces' },
  { id: 'bright-executive-office-wooden-desk-large-windows-greenery-41aedce6-hd', name: "Office Space #125", category: 'office-spaces' },
  { id: 'bright-industrial-workspace-large-windows-minimalist-desk-b9c637b7-hd', name: "Office Space #4", category: 'office-spaces' },
  { id: 'spacious-executive-office-marble-desk-large-windows-187a542b-hd', name: "Office Space #126", category: 'office-spaces' },
  { id: 'modern-office-large-windows-showcasing-lush-greenery-desk-ea0d32ef-hd', name: "Office Space #18", category: 'office-spaces' },
  { id: 'bright-office-glass-walls-wooden-desk-white-chair-large-3c4b280e-hd', name: "Office Space #127", category: 'office-spaces' },
  { id: 'executive-office-large-windows-revealing-city-skyline-warm-d1fb2999-hd', name: "Office Space #16", category: 'office-spaces' },
  { id: 'minimalist-office-space-light-colored-wall-black-shelves-b25c17ac-hd', name: "Office Space #5", category: 'office-spaces' },
  // home-office
  { id: 'cozy-home-office-wooden-desk-computer-displaying-landscape-d79a8759-hd', name: "Home Office #1", category: 'home-office' },
  { id: 'cozy-home-office-dual-monitors-wooden-desk-bookshelf-filled-7f901487-hd', name: "Home Office #3", category: 'home-office' },
  { id: 'home-office-white-cabinetry-two-monitors-bookshelves-view-33e1173d-hd', name: "Home Office #4", category: 'home-office' },
  { id: 'colorful-file-organizers-shelves-potted-succulents-desk-d3896424-hd', name: "Home Office #5", category: 'home-office' },
  { id: 'office-workspace-blue-binders-shelves-computer-plants-421fdd49-hd', name: "Home Office #8", category: 'home-office' },
  { id: 'modern-boardroom-wooden-desk-lamp-soft-curtains-illuminated-e1d043f6-hd', name: "Home Office #12", category: 'home-office' },
  { id: 'cozy-home-office-black-bookshelf-filled-books-decor-wooden-a655cb8a-hd', name: "Home Office #13", category: 'home-office' },
  { id: 'bright-desk-blue-binders-neatly-arranged-computer-greenery-17dc9404-hd', name: "Home Office #14", category: 'home-office' },
  { id: 'minimalist-boardroom-light-wood-cabinetry-sleek-computer-01d8b52f-hd', name: "Home Office #17", category: 'home-office' },
  { id: 'cozy-desk-stacked-books-small-potted-plant-coffee-cup-2160159c-hd', name: "Home Office #28", category: 'home-office' },
  { id: 'minimalist-shelf-displaying-potted-plants-stacked-books-6da7399b-hd', name: "Home Office #30", category: 'home-office' },
  { id: 'wooden-desk-laptop-stationery-bathed-natural-light-large-03f45b2a-hd', name: "Home Office #31", category: 'home-office' },
  { id: 'industrial-boardroom-exposed-brick-walls-large-windows-9aff17cd-hd', name: "Home Office #33", category: 'home-office' },
  { id: 'cozy-living-room-stone-fireplace-wooden-shelves-decorative-0fa4c54c-hd', name: "Home Office #34", category: 'home-office' },
  { id: 'minimalist-shelf-stacked-books-decorative-items-illuminated-174c5297-hd', name: "Home Office #36", category: 'home-office' },
  { id: 'cozy-home-office-wooden-desk-geometric-wall-art-warm-colors-39c668e5-hd', name: "Home Office #48", category: 'home-office' },
  { id: 'modern-office-large-wooden-desk-surrounded-bookshelves-lush-e20a391e-hd', name: "Home Office #50", category: 'home-office' },
  { id: 'bright-office-workspace-white-desk-computer-various-green-293c21ca-hd', name: "Home Office #61", category: 'home-office' },
  { id: 'bright-home-office-white-desk-computer-green-plants-ddb0ab97-hd', name: "Home Office #62", category: 'home-office' },
  { id: 'bright-minimalist-room-wooden-table-potted-plant-sheer-031a23b9-hd', name: "Home Office #69", category: 'home-office' },
  { id: 'minimalist-workspace-wooden-desk-two-potted-plants-large-c3bf5c42-hd', name: "Home Office #74", category: 'home-office' },
  { id: 'bright-interior-window-seat-cushions-light-curtains-wooden-f22dadc4-hd', name: "Home Office #76", category: 'home-office' },
  { id: 'sophisticated-home-office-dark-wood-furniture-globe-d290a9df-hd', name: "Home Office #80", category: 'home-office' },
  { id: 'spacious-boardroom-wooden-flooring-large-windows-minimalist-2d728fe2-hd', name: "Home Office #90", category: 'home-office' },
  { id: 'cozy-window-seat-soft-cushions-light-curtains-greenery-293df6b4-hd', name: "Home Office #92", category: 'home-office' },
  { id: 'calming-online-consultation-background-c-9cd754e4-hd', name: "Home Office #101", category: 'home-office' },
  { id: 'calming-therapy-office-virtual-background-c7794f51-hd', name: "Home Office #100", category: 'home-office' },
  { id: 'bright-home-office-white-desk-chair-large-windows-sheer-48445820-hd', name: "Home Office #63", category: 'home-office' },
  // nature-landscapes
  { id: 'wooden-deck-overlooking-mountain-range-trees-bathed-soft-e2f38223-hd', name: "Nature Landscape #12", category: 'nature-landscapes' },
  { id: 'rustic-wooden-deck-log-railings-overlooking-tranquil-lake-24fc7642-hd', name: "Nature Landscape #18", category: 'nature-landscapes' },
  { id: 'wooden-deck-railing-overlooking-green-hills-snow-capped-d993db39-hd', name: "Nature Landscape #46", category: 'nature-landscapes' },
  { id: 'lakeside-view-pine-trees-calm-water-distant-mountains-under-0b581437-hd', name: "Nature Landscape #75", category: 'nature-landscapes' },
  { id: 'scenic-mountain-view-autumn-trees-yellow-orange-wooden-sign-4d18aa11-hd', name: "Nature Landscape #11", category: 'nature-landscapes' },
  { id: 'rustic-wooden-deck-overlooking-calm-lake-surrounded-tall-260cbfdb-hd', name: "Nature Landscape #19", category: 'nature-landscapes' },
  { id: 'wooden-deck-overlooking-tranquil-lake-surrounded-mountains-ca007cac-hd', name: "Nature Landscape #20", category: 'nature-landscapes' },
  { id: 'modern-terrace-white-seating-overlooking-desert-landscape-dc2f713b-hd', name: "Nature Landscape #30", category: 'nature-landscapes' },
  { id: 'wooden-deck-railing-view-mountains-forest-under-clear-blue-4304e9eb-hd', name: "Nature Landscape #98", category: 'nature-landscapes' },
  { id: 'wooden-deck-railing-overlooking-green-mountains-under-warm-e7178e7e-hd', name: "Nature Landscape #99", category: 'nature-landscapes' },
  { id: 'rustic-stone-bench-sits-desert-viewpoint-surrounded-rocky-96546746-hd', name: "Nature Landscape #10", category: 'nature-landscapes' },
  // living-rooms
  { id: 'rustic-kitchen-large-fireplace-wooden-cabinets-cactus-plant-8492f8b0-hd', name: "Living Room #8", category: 'living-rooms' },
  { id: 'bright-coastal-living-room-white-sofa-wooden-coffee-table-d6083982-hd', name: "Living Room #10", category: 'living-rooms' },
  { id: 'cozy-living-room-white-sofa-wooden-accents-natural-light-42d781df-hd', name: "Living Room #11", category: 'living-rooms' },
  { id: 'cozy-reading-nook-chair-draped-blanket-bookshelf-filled-19113a58-hd', name: "Living Room #14", category: 'living-rooms' },
  { id: 'modern-lounge-glass-walls-wooden-furniture-view-greenery-8d467e1b-hd', name: "Living Room #17", category: 'living-rooms' },
  { id: 'bright-living-room-large-sectional-sofa-decorative-pillows-deea7879-hd', name: "Living Room #27", category: 'living-rooms' },
  { id: 'bright-modern-living-room-light-gray-sofa-wooden-coffee-5967e3d8-hd', name: "Living Room #46", category: 'living-rooms' },
  // kitchens
  { id: 'rustic-kitchen-wooden-cabinets-kettle-bowl-oranges-small-eefd9f60-hd', name: "Kitchen #4", category: 'kitchens' },
  { id: 'bright-kitchen-coffee-machine-marble-countertop-natural-897fbffb-hd', name: "Kitchen #5", category: 'kitchens' },
  { id: 'bright-kitchen-stainless-steel-appliances-light-cabinetry-1378ae42-hd', name: "Kitchen #6", category: 'kitchens' },
  { id: 'cozy-kitchen-marble-countertops-wooden-cabinets-natural-eff10841-hd', name: "Kitchen #14", category: 'kitchens' },
  { id: 'modern-kitchen-concrete-cabinets-wooden-accents-large-2e86b30d-hd', name: "Kitchen #15", category: 'kitchens' },
  { id: 'spacious-modern-kitchen-wood-cabinets-large-windows-natural-f3113907-hd', name: "Kitchen #16", category: 'kitchens' },
  // gardens-patios
  { id: 'serene-corner-blue-white-walls-terracotta-pots-vibrant-1959e32a-hd', name: "Garden & Patio #1", category: 'gardens-patios' },
  { id: 'vibrant-courtyard-orange-walls-potted-plants-sunny-051dd8cf-hd', name: "Garden & Patio #12", category: 'gardens-patios' },
  { id: 'garden-pathway-lined-lavender-colorful-flowers-leading-white-07df2d59-hd', name: "Garden & Patio #14", category: 'gardens-patios' },
  // christmas-backgrounds
  { id: 'rustic-living-room-brown-sofa-plaid-pillows-christmas-tree-0bfafc09-hd', name: "Christmas #35", category: 'christmas-backgrounds' },
  // easter-backgrounds
  { id: 'three-shelves-display-pastel-vases-tulips-white-bunny-basket-f7f6f9bc-hd', name: "Easter #3", category: 'easter-backgrounds' },
  { id: 'white-shelf-colorful-easter-eggs-wicker-basket-filled-eggs-85cb8cbe-hd', name: "Easter #4", category: 'easter-backgrounds' },
  { id: 'bright-kitchen-corner-vase-white-lilies-greenery-wooden-403e7e9b-hd', name: "Easter #101", category: 'easter-backgrounds' },
  { id: 'boardroom-large-wooden-table-leather-chairs-floor-ceiling-bc6c684a-hd', name: "Easter #21", category: 'easter-backgrounds' },
  { id: 'well-organized-office-wooden-desk-colorful-books-basket-eggs-d3fba909-hd', name: "Easter #32", category: 'easter-backgrounds' },
  { id: 'cozy-office-wooden-desk-basket-colorful-eggs-vibrant-tulips-9475782b-hd', name: "Easter #35", category: 'easter-backgrounds' },
  { id: 'cozy-home-office-wooden-desk-chair-large-windows-letting-caccf1b2-hd', name: "Easter #39", category: 'easter-backgrounds' },
  { id: 'cozy-library-white-shelves-filled-books-soft-lighting-floral-8c5ce83b-hd', name: "Easter #42", category: 'easter-backgrounds' },
  { id: 'wooden-table-vase-tulips-decorative-bunny-basket-colorful-9f60d3cd-hd', name: "Easter #48", category: 'easter-backgrounds' },
  { id: 'bright-kitchen-white-wooden-shelves-pastel-dishes-bowl-dabe6982-hd', name: "Easter #56", category: 'easter-backgrounds' },
  { id: 'bright-kitchen-wooden-table-decorative-rabbit-figurine-fe3b6007-hd', name: "Easter #57", category: 'easter-backgrounds' },
  { id: 'light-wood-shelves-wooden-rabbit-candles-vase-tulips-bowl-9eea306e-hd', name: "Easter #61", category: 'easter-backgrounds' },
  { id: 'well-composed-shelf-light-wood-pastel-eggs-white-tulips-b6f9dcf8-hd', name: "Easter #66", category: 'easter-backgrounds' },
  { id: 'cozy-nook-colorful-bookshelves-decorative-bunny-soft-natural-6a150e26-hd', name: "Easter #72", category: 'easter-backgrounds' },
  { id: 'well-lit-bookshelf-pastel-easter-decorations-basket-eggs-401c9c47-hd', name: "Easter #74", category: 'easter-backgrounds' },
  { id: 'wooden-shelf-rabbit-figurine-flowers-pot-decorative-eggs-6cca6c41-hd', name: "Easter #75", category: 'easter-backgrounds' },
  { id: 'bright-white-shelving-unit-potted-flowers-greenery-wooden-574a47e3-hd', name: "Easter #91", category: 'easter-backgrounds' },
  { id: 'minimalist-white-shelf-potted-plant-books-cross-illuminated-5957346f-hd', name: "Easter #92", category: 'easter-backgrounds' },
  { id: 'two-white-shelves-green-plant-white-flowers-candle-cross-427b61ff-hd', name: "Easter #93", category: 'easter-backgrounds' },
  { id: 'bright-kitchen-corner-large-windows-fresh-flowers-vase-c5c69f3d-hd', name: "Easter #99", category: 'easter-backgrounds' },
  { id: 'bright-window-scene-pastel-flowers-decorative-bunnies-d9103cc4-hd', name: "Easter #2", category: 'easter-backgrounds' },
  { id: 'glass-shelves-displaying-white-tulips-ceramic-bunny-candles-bfe66080-hd', name: "Easter #59", category: 'easter-backgrounds' },
  { id: 'dark-bookshelf-filled-books-decorative-bunnies-woven-basket-2542ffd9-hd', name: "Easter #87", category: 'easter-backgrounds' },
  { id: 'modern-office-white-desk-green-walls-bookshelves-filled-45295e97-hd', name: "Easter #106", category: 'easter-backgrounds' },
  // spring-backgrounds
  { id: 'minimalist-interior-floating-shelves-books-vase-flowers-f4d3d971-hd', name: "Spring #55", category: 'spring-backgrounds' },
  { id: 'bright-room-large-windows-showcasing-vibrant-green-trees-ea9afee3-hd', name: "Spring #63", category: 'spring-backgrounds' },
  { id: 'bright-reading-nook-white-shelves-filled-books-potted-plants-47811967-hd', name: "Spring #74", category: 'spring-backgrounds' },
  // neutral-backgrounds
  { id: 'professional-virtual-backdrop-c-bc46b971-hd', name: "Neutral Backgrounds #1", category: 'neutral-backgrounds' },
  { id: 'seamless-video-call-background-d4a783bf-hd', name: "Neutral Backgrounds #2", category: 'neutral-backgrounds' },
  // summer-backgrounds
  { id: 'coastal-living-room-white-sofas-blue-cushions-wooden-coffee-cdc74411-hd', name: "Summer Backgrounds #100", category: 'summer-backgrounds' },
  { id: 'serene-tropical-beach-view-turquoise-waters-white-sand-palm-382c1cb1-hd', name: "Summer Backgrounds #13", category: 'summer-backgrounds' },
  { id: 'tropical-beach-thatched-umbrella-lounge-chairs-soft-sand-2f83afd9-hd', name: "Summer Backgrounds #21", category: 'summer-backgrounds' },
  { id: 'beachfront-lounge-area-wooden-furniture-palm-trees-vibrant-abc14838-hd', name: "Summer Backgrounds #22", category: 'summer-backgrounds' },
  { id: 'coastal-patio-two-wooden-chairs-view-ocean-clear-blue-sky-67bb5908-hd', name: "Summer Backgrounds #36", category: 'summer-backgrounds' },
  { id: 'serene-courtyard-chaise-lounge-vibrant-bougainvillea-soft-08dba43c-hd', name: "Summer Backgrounds #1", category: 'summer-backgrounds' },
  { id: 'coastal-deck-wooden-furniture-soft-cushions-view-ocean-92ce82a2-hd', name: "Summer Backgrounds #28", category: 'summer-backgrounds' },
  { id: 'bright-coastal-view-through-sheer-curtains-revealing-51db4940-hd', name: "Summer Backgrounds #31", category: 'summer-backgrounds' },
  { id: 'bright-office-space-light-wood-shelves-filled-books-view-44697c96-hd', name: "Summer Backgrounds #32", category: 'summer-backgrounds' },
  { id: 'well-lit-desk-vase-flowers-books-lamp-view-mountains-through-6cad8df1-hd', name: "Summer Backgrounds #35", category: 'summer-backgrounds' },
  { id: 'bright-boardroom-wooden-tables-sheer-curtains-ocean-view-fcc8f347-hd', name: "Summer Backgrounds #37", category: 'summer-backgrounds' },
  { id: 'cozy-conservatory-filled-lush-plants-comfortable-sofa-255a65c8-hd', name: "Summer Backgrounds #38", category: 'summer-backgrounds' },
  { id: 'coastal-retreat-woven-chairs-light-curtains-view-turquoise-d9e8471a-hd', name: "Summer Backgrounds #14", category: 'summer-backgrounds' },
  { id: 'composed-camera-modern-japanese-engawa-ae4eb8ad-hd', name: "Summer Backgrounds #101", category: 'summer-backgrounds' },
  { id: 'composed-camera-high-end-lakeside-cabin-63a25917-hd', name: "Summer Backgrounds #102", category: 'summer-backgrounds' },
];

export const HD_BASE_IDS = new Set(HD_PRODUCTS.map((p) => p.slug || p.id.replace(/-hd$/, '')));
